### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by DenZhid** [DenZhid/PolyActive#21]
- [x] При входе в fragment_feed из fragment_login не отображается Toolbar
- [x] При повороте экрана login приложение вылетает
- [x] При повороте экрана profile приложение вылетает
- [x] Если выйти из аккаунта и зайти с помощью кнопки "Войти", то будут отображаться старые данные с прошлого аккаунта Gooogle
- [x] Не сохраняется состояние выбранных групп при повороте экрана
- [x] В FeedFragment binding создаётся в некорректном месте, из-за чего приложение иногда крашиться (после изменения языка или повороте экрана, к примеру)
- [x] Неправильное отображение названий вкладок для русской раскладки
- [x] При входе в fragment_feed из fragment_login подсвечивается неправильная вкладка
- [x] Не сохраняется положение RecyclerView при повороте экрана или переходе на другой фрамгент.
- [x] Не сохраняется выбранная вкладка FeedFragment при повороте экрана или переходе на другой фрамгент.
- [x] При выходе с помощью UpNavigation из NewsViewer не возвращаемся в feed
- [x] Можно улучшить версию тёмной темы
- [x] При многократном нажатии на Feed вкладку в botttomNav приложение вылетает
- [x] Приложение вылетает в случае отсутствия Интернета при первом входе (поскольку кэш пуст)
- [x] Последняя новость не видна за BottomNavigation
- [ ] Парсируемые новости не фильтруются (нужно проверять на отсутствие ссылок по типу [club9133] и т. п.)
- [ ] Нет возможности просмотра более ранних новостей
- [ ] Нет обновления новостей при landscape

**Comment by zadorotskas** [comment]
- [x] При смене языка или темы в настройках в тулбаре наверху появляется надпись Новости/News (а не Настройки/Settings)

**Comment by a-yasevich** [comment]
- [x] В FeedFragment при каждом вызове onStart() у NewsAdapter срабатывает метод addAllItems и в newsList повторно добавляются новости

**Comment by DenZhid** [comment]
Работа над проектом окончена
